module.exports = {
  // parser: 'babel-eslint',
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: "module",
    ecmaFeatures: {
      jsx: true,
    },
  },
  env: {
    node: true,
    browser: true,
    jest: true,
  },
  // extends: ['prettier'],
  rules: {
    // Possible Errors
    "for-direction": "error",
    "getter-return": "error",
    "no-async-promise-executor": "error",
    "no-await-in-loop": "off",
    "no-compare-neg-zero": "error",
    "no-cond-assign": ["error", "always"],
    "no-console": ["warn"],
    "no-constant-condition": ["error"],
    "no-control-regex": ["error"],
    "no-debugger": ["error"],
    "no-dupe-args": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": "error",
    "no-empty-character-class": "error",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "error",
    "no-extra-parens": "error",
    "no-extra-semi": "error",
    "no-func-assign": "error",
    "no-import-assign": "error",
    "no-inner-declarations": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-misleading-character-class": "error",
    "no-obj-calls": "error",
    "no-prototype-builtins": "error",
    "no-regex-spaces": "error",
    "no-setter-return": "error",
    "no-sparse-arrays": "error",
    "no-template-curly-in-string": "off",
    "no-unexpected-multiline": "error",
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-useless-backreference": "error",
    "require-atomic-updates": "error",
    "use-isnan": "error",
    "valid-typeof": "error",

    // Best practices
    "accessor-pairs": "off",
    "block-scoped-var": "error",
    "class-methods-use-this": [
      "error",
      {
        exceptMethods: [],
      },
    ],
    "array-callback-return": ["error", { allowImplicit: true }],
    // class-methods-use-this
    complexity: [
      "error",
      {
        max: 20,
      },
    ],
    "consistent-return": "error",
    curly: ["error", "multi-line"],
    "default-case": "error",
    "default-case-last": "error",
    "default-param-last": "off",
    "dot-location": "error",
    "dot-notation": "error",
    eqeqeq: ["error", "always"],
    "grouped-accessor-pairs": "error",
    "guard-for-in": "error",
    "max-classes-per-file": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-named-capture-group": "off",
    "no-alert": "off",
    " no-caller": "error",
    "no-case-declarations": "error",
    "no-constructor-return": "error",
    "no-div-regex": "error",
    "no-else-return": "error",
    "no-empty-function": "error",
    "no-empty-pattern": "error",
    "no-eq-null": "error",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-extra-label": "error",
    "no-fallthrough": "error",
    "no-floating-decimal": "error",
    "no-global-decimal": "error",
    "no-implicit-coercion": "error",
    "no-implicit-globals": "error",
    "no-implied-eval": "error",
    "no-invalid-this": "error",
    "no-iterator": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-loop-func": "error",
    "no-magic-numbers": [
      "off",
      {
        ignore: [],
        ignoreArrayIndexes: true,
        enforceConst: true,
        detectObjects: false,
      },
    ],
    "no-multi-spaces": "error",
    "no-multi-str": "error",
    "no-native-reassign": "error",
    "no-new": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-octal": "error",
    "no-octal-escape": "error",
    "no-param-reassign": "error",
    "no-proto": "error",
    "no-redeclare": "error",
    "no-return-assign": ["error", "except-parens"],
    "no-script-url": "error",
    "no-self-assign": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-throw-literal": "error",
    "no-unmodified-loop-condition": "error",
    "no-unused-expressions": "error",
    "no-unused-labels": "error",
    "no-useless-call": "error",
    "no-useless-concat": "error",
    "no-useless-escape": "error",
    "no-void": "error",
    "no-warning-comments": "error",
    "no-with": "error",
    radix: "error",
    "require-await": "off",
    "require-unicode-regexp": "off",
    "vars-on-top": "error",
    "wrap-iife": "error",
    yoda: "error",

    // Strict mode
    strict: "error",

    // Variables
    "init-declarations": "error",
    "no-delete-var": "error",
    "no-label-var": "error",
    "no-restricted-globals": "error",
    "no-shadow": "error",
    "no-shadow-restricted-names": "error",
    "no-undef": "error",
    "no-undef-init": "error",
    "no-undefined": "error",
    "no-unused-vars": "error",
    "no-use-before-define": "error",

    // Stylistic issues
    "array-bracket-newline": "error",
    "array-bracket-spacing": "error",
    "array-element-newline": "off",
    "block-spacing": "error",
    "brace-style": "error",
    camelcase: ["error", { properties: "always" }],
    "capitalized-comments": "off",
    "comma-dangle": [
      "error",
      {
        arrays: "always-multiline",
        objects: "always-multiline",
        imports: "always-multiline",
        exports: "always-multiline",
        functions: "always-multiline",
      },
    ],
    "comma-spacing": "error",
    "comma-style": "error",
    "computed-property-spacing": "error",
    "consistent-this": "off",
    "eol-last": "error",
    "func-call-spacing": "error",
    "func-name-matching": "error",
    "func-names": "error",
    "func-style": "off",
    "function-paren-newline": "error",
    "id-blacklist": "error",
    "id-length": "off",
    "id-match": [
      "error",
      // camelCase, PascalCase, __filename, CONST_VALUE, stream$, $el
      "^\\$?(__)?(([A-Z]|[a-z]|[0-9]+)|([A-Z_]))*\\$?$",
    ],
    "implicit-arrow-linebreak": "error",
    indent: ["error", 2],
    "jsx-quotes": "error",
    "key-spacing": "error",
    "keyword-spacing": "error",
    "line-comment-position": "off",
    "linebreak-style": "error",
    "lines-between-class-members": "off",
    "max-depth": ["error", 4],
    "max-len": "error",
    "max-lines": [
      "error",
      { max: 2500, skipBlankLines: false, skipComments: false },
    ],
    "max-lines-per-function": ["error", 150],
    "max-nested-callbacks": ["error", 7],
    "max-params": ["error", 7],
    "max-statements": ["error", 40],
    "max-statements-per-line": ["error", { max: 1 }],
    "multiline-comment-style": "off",
    "multiline-ternary": "error",
    "new-cap": "error",
    "new-parens": "error",
    "newline-per-chained-call": "error",
    "no-array-constructor": "error",
    "no-bitwise": "error",
    "no-continue": "error",
    "no-inline-comments": "off",
    "no-lonely-if": "error",
    "no-multi-assign": "error",
    "no-negated-condition": "error",
    "no-nested-ternary": "off",
    "no-new-object": "error",
    "no-plusplus": "off",
    "no-restricted-syntax": ["error", "WithStatement"],
    "no-ternary": "off",
    "no-underscore-dangle": "off",
    "no-tabs": "error",
    "no-trailing-spaces": "error",
    "no-unneeded-ternary": "error",
    "no-mixed-operators": "error",
    "no-multiple-empty-lines": "error",
    "no-mixed-spaces-and-tabs": "error",
    "one-var": ["error", { uninitialized: "always", initialized: "never" }],
    "operator-assignment": "error",
    "no-whitespace-before-property": "error",
    "nonblock-statement-body-position": "error",
    "object-curly-newline": "error",
    "object-curly-spacing": "off",
    "object-property-newline": "off",
    "one-var-declaration-per-line": "error",
    "operator-linebreak": "error",
    "padded-blocks": "error",
    "no-restricted-properties": "error",
    "no-return-await": "error",
    "padding-line-between-statements": "error",
    "prefer-exponentiation-operator": "warn",
    "prefer-object-spread": "error",
    "sort-keys": "off",
    "sort-vars": "error",
    "quote-props": ["error", "as-needed"],
    quotes: "error",
    semi: "error",
    "semi-spacing": "error",
    "semi-style": "error",
    "space-before-blocks": "error",
    "space-before-function-paren": "error",
    "spaced-comment": "error",
    "switch-colon-spacing": "error",
    "space-in-parens": "error",
    "space-infix-ops": "error",
    "space-unary-ops": "error",
    "template-tag-spacing": "error",
    "unicode-bom": "error",
    "wrap-regex": "error",

    // ECMAScript 6
    "arrow-body-style": "error",
    "arrow-parens": "error",
    "arrow-spacing": "error",
    "constructor-super": "error",
    "generator-star-spacing": "error",
    "no-class-assign": "error",
    "no-confusing-arrow": "error",
    "no-const-assign": "error",
    "no-dupe-class-members": "error",
    "no-duplicate-imports": "error",
    "no-new-symbol": "error",
    "no-restricted-exports": "error",
    "no-restricted-imports": "error",
    "no-this-before-super": "error",
    "no-useless-computed-key": "error",
    "no-useless-constructor": "error",
    "no-useless-rename": "error",
    "no-var": "error",
    "object-shorthand": "error",
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "prefer-destructuring": "error",
    "prefer-numeric-literals": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    "require-yield": "error",
    "rest-spread-spacing": "error",
    "sort-imports": "error",
    "symbol-description": "error",
    "template-curly-spacing": "error",
    "yield-star-spacing": "error",

    // Deprecated
    // callback-return
    // global-require
    // handle-callback-err
    // lines-around-comment
    // no-buffer-constructor
    // no-caller
    // no-global-assign
    // no-mixed-requires
    // no-new-require
    // no-path-concat
    // no-process-env
    // no-process-exit
    // no-restricted-modules
    // no-sync
    // no-useless-catch
    // no-useless-return
  },
};
