'use strict';

module.exports = {
  parserOptions: {
    ecmaVersion: 2020,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  env: {
    es2020: true,
    node: true,
    browser: true,
  },
  rules: {
    // POSSIBLE ERRORS
    // no-cond-assign:
    // no-console:
    // no-constant-condition:
    // no-control-regex:
    // no-debugger:
    // no-dupe-args:
    // no-dupe-keys:
    // no-duplicate-case:
    // no-empty:
    // no-empty-character-class:
    // no-ex-assign:
    // no-extra-boolean-cast:
    // no-extra-parens:
    // no-extra-semi:
    // no-func-assign:
    // no-inner-declarations:
    // no-invalid-regexp:
    // no-irregular-whitespace:
    // no-negated-in-lhs:
    // no-obj-calls:
    // no-prototype-builtins:
    // no-regex-spaces:
    // no-sparse-arrays:
    // no-unexpected-multiline:
    // no-unreachable:
    // no-unsafe-finally:
    // use-isnan:
    // valid-jsdoc:
    // valid-typeof:
    // BEST PRACTICES
    // accessor-pairs:
    // array-callback-return:
    // block-scoped-var:
    // complexity:
    // consistent-return:
    // curly:
    // default-case:
    // dot-location:
    // dot-notation:
    // eqeqeq:
    // guard-for-in:
    // no-alert:
    // no-caller:
    // no-case-declarations:
    // no-div-regex:
    // no-else-return:
    // no-empty-function:
    // no-empty-pattern:
    // no-eq-null:
    // no-eval:
    // no-extend-native:
    // no-extra-bind:
    // no-extra-label:
    // no-fallthrough:
    // no-floating-decimal:
    // no-implicit-coercion:
    // no-implicit-globals:
    // no-implied-eval:
    // no-invalid-this:
    // no-iterator:
    // no-labels:
    // no-lone-blocks:
    // no-loop-func:
    // no-magic-numbers:
    // no-multi-spaces:
    // no-multi-str:
    // no-native-reassign:
    // no-new:
    // no-new-func:
    // no-new-wrappers:
    // no-octal:
    // no-octal-escape:
    // no-param-reassign:
    // no-proto:
    // no-redeclare:
    // no-return-assign:
    // no-script-url:
    // no-self-assign:
    // no-self-compare:
    // no-sequences:
    // no-throw-literal:
    // no-unmodified-loop-condition:
    // no-unused-expressions:
    // no-unused-labels:
    // no-useless-call:
    // no-useless-concat:
    // no-useless-escape:
    // no-void:
    // no-warning-comments:
    // no-with:
    // radix:
    // vars-on-top:
    // wrap-iife:
    // yoda:
    // STRICT MODE
    // strict
    // VARIABLES
    // init-declarations:
    // no-catch-shadow:
    // no-delete-var:
    // no-label-var:
    // no-restricted-globals:
    // no-shadow:
    // no-shadow-restricted-names:
    // no-undef:
    // no-undef-init:
    // no-undefined:
    // no-unused-vars:
    // no-use-before-define:
    // Node.js and CommonJS
    // callback-return:
    // global-require:
    // handle-callback-err:
    // no-mixed-requires:
    // no-new-require:
    // no-path-concat:
    // no-process-env:
    // no-process-exit:
    // no-restricted-modules:
    // no-sync:
    // Stylistic Issues
    // array-bracket-spacing:
    // block-spacing:
    // brace-style:
    // camelcase:
    // comma-dangle:
    // comma-spacing:
    // comma-style:
    // computed-property-spacing:
    // consistent-this:
    // eol-last:
    // func-names:
    // func-style:
    // id-blacklist:
    // id-length:
    // id-match:
    // indent:
    // jsx-quotes:
    // key-spacing:
    // keyword-spacing:
    // linebreak-style:
    // lines-around-comment:
    // max-depth:
    // max-len:
    // max-lines:
    // max-nested-callbacks:
    // max-params:
    // max-statements:
    // max-statements-per-line:
    // multiline-ternary:
    // new-cap:
    // new-parens:
    // newline-after-var:
    // newline-before-return:
    // newline-per-chained-call:
    // no-array-constructor:
    // no-bitwise:
    // no-continue:
    // no-inline-comments:
    // no-lonely-if:
    // no-mixed-operators:
    // no-mixed-spaces-and-tabs:
    // no-multiple-empty-lines:
    // no-negated-condition:
    // no-nested-ternary:
    // no-new-object:
    // no-plusplus:
    // no-restricted-syntax:
    // no-spaced-func:
    // no-ternary:
    // no-trailing-spaces:
    // no-underscore-dangle:
    // no-unneeded-ternary:
    // no-whitespace-before-property:
    // object-curly-newline:
    // object-curly-spacing:
    // object-property-newline:
    // one-var:
    // one-var-declaration-per-line:
    // operator-assignment:
    // operator-linebreak:
    // padded-blocks:
    // quote-props:
    // quotes:
    // require-jsdoc:
    // semi:
    // semi-spacing:
    // sort-vars:
    // space-before-blocks:
    // space-before-function-paren:
    // space-in-parens:
    // space-infix-ops:
    // space-unary-ops:
    // spaced-comment:
    // unicode-bom:
    // wrap-regex:
    // ECMAScript 6
    // arrow-body-style:
    // arrow-parens:
    // arrow-spacing:
    // constructor-super:
    // generator-star-spacing:
    // no-class-assign:
    // no-confusing-arrow:
    // no-const-assign:
    // no-dupe-class-members:
    // no-duplicate-imports:
    // no-new-symbol:
    // no-restricted-imports:
    // no-this-before-super:
    // no-useless-computed-key:
    // no-useless-constructor:
    // no-useless-rename:
    // no-var:
    // object-shorthand:
    // prefer-arrow-callback:
    // prefer-const:
    // prefer-reflect:
    // prefer-rest-params:
    // prefer-spread:
    // prefer-template:
    // require-yield:
    // rest-spread-spacing:
    // sort-imports:
    // template-curly-spacing:
    // yield-star-spacing:
  },
};
